name: '更新数据'

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
    branches:
      - main

jobs:
  push:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-20.04']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pipenv --python 3
          pipenv install --deploy --ignore-pipfile

      - name: Install Selenium
        run: |
          sudo pip3 install selenium

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Download chrome driver
        uses: nanasess/setup-chromedriver@master

      - name: Launch chrome driver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Set final file name
        id: set_final_file_name
        run: echo "::set-output name=final_file::$(python -c 'import config; print(config.final_file)')"

      - name: Build
        run: pipenv run build
      
      - name: Commit changes
        run: |
          git config --local user.email "yuan.lr.yaa@gmail.com"
          git config --local user.name "LR"
          git add .
          git diff --quiet || git commit -am "Github Action Auto Updated"
          git push
